---
title: "week 5 assignment 1"
author: "Yuyu"
date: "2019-02-01"
output:
  pdf_document: default
  html_document: default
---
#### A. Set Up

1. Load the `haven`, `tidyverse`, `ggeffects` and `ipumsr` packages
```{r, message=FALSE}
library(tidyverse)
library(haven)
library(ggeffects)
library(ipumsr)
```


2. Read in the `ipumsi_00010.dta`
```{r}
d0 <- read_dta("C:/Users/18800/Desktop/stat model/data/ipumsi_00011.dta")
head(d0)
```

3. Create the `mis_lab` object 

```{r}
mis_labs <- c("unknown", 
              "niu (not in universe)",
              # age
              "not reported/missing", 
              # marst and nativity
              "unknown/missing")
```

4. clean the data
```{r}
d1 <- d0 %>%
  select( marst, age, sex, race, year) %>%
  mutate_if(is.labelled, lbl_clean) %>%
  mutate_if(is.labelled, funs(lbl_na_if(., ~.lbl %in% mis_labs))) %>%
  mutate_at(vars(age), zap_labels) %>%
  mutate_if(is.labelled, as_factor)
d1
```

#### transform data format 
### modify varibles

```{r}
summary(d1$race)
d1 <- d1 %>%
  mutate(married = ifelse(test = marst %in% c("married/in union"),
                           yes = 1, no = 0)) %>%
  mutate(age=as.numeric(age),
         c_age = age - mean(age, na.rm = TRUE),
         z_age = (age - mean(age, na.rm = TRUE))/sd(age, na.rm = TRUE),
         racies=case_when(race=="white"~"white",
                          race=="black"~"black",
                          race %in% c("chinese","japanese","korean ","vietnamese","filipino","indian","pakistani","bangladeshi","other asian" )~"asian"))%>%
  filter(marst==c("married/in union","single/never married"))%>%
  mutate(racies=as.factor(racies))
d1

summary(d1$racies)
```
### look at the data
```{r}
d2 <- d1 %>%
  filter(age >= 18)
d2 %>% 
  filter(year == 2015) %>%
  summary()

```
### build models


```{r}
m3 <- glm(formula = married ~ age * sex * racies,
          data = filter(d2, year == 2015),
          family = "binomial")
arm::display(m3)
summary(m3)
library(ggfortify)
autoplot(m3)
```
### plot model coefficients
```{r}
m4 <- glm(formula = married ~ c_age + c_age^3 * sex * racies,
          data = filter(d2, year == 2010),
          family = "binomial")
library(ggfortify)
arm::binnedplot(x = predict(m4, type = "response"), 
                y = resid(m4, type = "response"))
arm::binnedplot(x = predict(m4, type = "response"), 
                y = resid(m4, type = "response"), 
                nclass = 100)
arm::binnedplot(x = m4$data$age, 
                y = resid(m4, type = "response"), 
                nclass = 100)
```

```{r}

m5 <- d2 %>%
  group_by(year) %>%
  do(m = glm(formula = married ~ c_age*sex * racies, data = ., family = "binomial")) %>%
  broom::tidy(m) %>%
  mutate(term = fct_inorder(term))

ggplot(data = m5,
       mapping = aes(x = year, y = estimate,
                     ymin = estimate + qnorm(0.1) * std.error,
                     ymax = estimate + qnorm(0.9) * std.error)) +
  facet_wrap("term", scales = "free") +
  geom_point() +
  geom_pointrange() +
  geom_hline(yintercept = 0)
```
```{r}

formula(m3)

m6 <- d2 %>%
  group_by(year) %>%
  do(m = glm(formula = formula(m3), data = ., family = "binomial"))
```
### plot predictation for each model
```{r}
for(i in 1:3){
  m6$m[[i]] %>%
    ggpredict(terms = c("age", "racies",  "sex")) %>%
    plot(limits = c(0, 1.0)) %>%
    print()
}
```
```{r}

```

